### ISSUE TITLE
btn_conditioner unusable, makes Kotlin crash

### ISSUE THREAD

**Issue by dheijl** [alchitry/Alchitry-Labs-V2#35]
When I try to instantiate a button_conditioner in alchitry_top, the IDE insists that I provide a #CLK_FREQ.

Any attempt  to do this results in:
```
Index 1 out of bounds for length 1
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)	
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)	
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)	
at java.base/java.util.Objects.checkIndex(Objects.java:359)	at java.base/java.util.ArrayList.get(ArrayList.java:427)	
at com.alchitry.labs2.parsers.hdl.lucid.parsers.SignalParser.exitSignal(SignalParser.kt:122)	
at com.alchitry.labs2.parsers.grammar.LucidParser$SignalContext.exitRule(LucidParser.kt:5988)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.exitRule(ParseTreeMultiWalker.kt:111)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk(ParseTreeMultiWalker.kt:46)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk$default(ParseTreeMultiWalker.kt:10)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk(ParseTreeMultiWalker.kt:44)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk$default(ParseTreeMultiWalker.kt:10)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk(ParseTreeMultiWalker.kt:44)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk$default(ParseTreeMultiWalker.kt:10)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk(ParseTreeMultiWalker.kt:44)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk$default(ParseTreeMultiWalker.kt:10)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk(ParseTreeMultiWalker.kt:44)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk$default(ParseTreeMultiWalker.kt:10)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk(ParseTreeMultiWalker.kt:44)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk$default(ParseTreeMultiWalker.kt:10)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk(ParseTreeMultiWalker.kt:44)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk$default(ParseTreeMultiWalker.kt:10)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk(ParseTreeMultiWalker.kt:44)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk$default(ParseTreeMultiWalker.kt:10)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk(ParseTreeMultiWalker.kt:44)	
at com.alchitry.labs2.parsers.ParseTreeMultiWalker.walk$default(ParseTreeMultiWalker.kt:10)	
at com.alchitry.labs2.parsers.hdl.lucid.context.LucidBlockContext.walk(LucidBlockContext.kt:214)	
at com.alchitry.labs2.parsers.hdl.lucid.context.LucidBlockContext.walk$default(LucidBlockContext.kt:213)	
at com.alchitry.labs2.parsers.hdl.lucid.context.LucidBlockContext.initialWalk(LucidBlockContext.kt:200)	
at com.alchitry.labs2.parsers.hdl.types.ModuleInstance.initialWalk(ModuleInstance.kt:48)	
at com.alchitry.labs2.project.Project.buildContext(Project.kt:554)	
at com.alchitry.labs2.project.Project$buildContext$1.invokeSuspend(Project.kt)	
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)	
at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)	
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)	
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)	
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)	
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:832)	
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)	
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@ef76ae2, Dispatchers.Default]
Index 1 out of bounds for length 1
Index 1 out of bounds for length 1
```
The editor is also less than overwhelming. A VSCode plugin would have been so much nicer...

The board  itself (Alchitry AU kit) itself is excellent.

**Comment by dheijl** [comment]
I can't reproduce it any more, so closing it.
